In [1]:
## Load the numpy library
import numpy as np

### The basics

In [2]:
a = np.array([1,2,3])


In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
## Get dimensions
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get type
a.dtype

dtype('int32')

In [10]:
a1 = np.array([1,2,3], dtype='int16')
print(a1)

[1 2 3]


In [11]:
## Taking less space than the default value of int
a1.dtype

dtype('int16')

In [12]:
## Returns the size in bytes of each element of a NumPy array
a.itemsize

4

In [13]:
a1.itemsize

2

In [14]:
# Get total size 
# (Basically counts the number of elements present in a numpy array)
a.size

3

In [15]:
# We can see the total value of this combination
a.size * a.itemsize

12

In [16]:
# To return the above value as a function
a.nbytes

12

### Accessing/Changing specific elements, rows, columns etc

In [17]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [19]:
# Get a specific element [r,c]
a[1,5]

13

In [20]:
a[1,-2]

13

In [21]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column
a[:, 3]

array([ 4, 11])

In [23]:
# [startindex : endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [24]:
a[0, 1:-1:2]

array([2, 4, 6])

In [25]:
# change some value in array
# it first considers the row number and then considers the column number
a[1,5] = 20

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [27]:
# Considering all the rows 
# but the column number is actually 3rd (Numpy no of 2)
a[:,2] = 5

In [28]:
# Doing the same as above but for two values
a[:,2] = [1,2]

In [29]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [30]:
## 3D Example
b1 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [31]:
b1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
## Get specific element (work outside in)
b1[0,1,1]

4

In [33]:
b1[:,1,:]

array([[3, 4],
       [7, 8]])

In [34]:
b1[:,0,1]

array([2, 6])

In [35]:
b1[:,0,:]

array([[1, 2],
       [5, 6]])

In [36]:
# replace in 3D
b1[:,1,:] = [[9,9], [8,8]]

In [37]:
b1

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [38]:
b1[1,0,:]

array([5, 6])

In [39]:
b1[0,0,0]

1

In [40]:
b1[0,0,1]

2

In [41]:
b1[0,1,0]

9

In [42]:
b1[0,1,1]

9

In [43]:
b1[1,:,:]

array([[5, 6],
       [8, 8]])

In [44]:
b1

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [45]:
b1[1,0,:]

array([5, 6])

In [46]:
b1[1,-1,:]

array([8, 8])

### Initializing different types of arrays

In [47]:
# All 0s matrix
np.zeros((1,2))

array([[0., 0.]])

In [48]:
np.zeros((2,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [49]:
# All 1s matrix
np.ones((1,2))

array([[1., 1.]])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# any other number
# first it takes the dimensional shape [r,c] 
# and then it takes the value as input
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [52]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [53]:
# any other number (full-like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
#Random decimal numbers

np.random.rand(4,2)

array([[0.20403865, 0.20317239],
       [0.08439586, 0.06577996],
       [0.01716027, 0.70717436],
       [0.89003326, 0.42503879]])

In [55]:
np.random.random_sample(a.shape)

array([[0.84327835, 0.20861256, 0.95440877, 0.98683084, 0.56864194,
        0.23832019, 0.76476077],
       [0.90213972, 0.00265296, 0.57330779, 0.06992249, 0.17559838,
        0.29721786, 0.42623108]])

In [56]:
# Random Integer Values
# the '4' represents the starting value 
# and the '6' represents the value which will be excluded so we will have till 5
np.random.randint(4,6, size=(3,3))

array([[4, 5, 5],
       [5, 5, 5],
       [4, 4, 5]])

In [57]:
# Identity Matrix
# Here we are putting '1' as diagonal values 
# whereas all other values are zeros, basically in binary configuration
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [59]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [60]:
n = np.ones((5,5), dtype='int16')

In [61]:
n[1:-1,1:-1] = 0

In [62]:
n[2,2] = 9

In [63]:
n

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [64]:
# Be careful while copying
q = np.array([1,2,3,4])

w = q
w[1] = -1
print(w)
print(q)

[ 1 -1  3  4]
[ 1 -1  3  4]


In [65]:
e = np.array([1,2,3,4])

r = e.copy()
r[1] = -1
print(r)
print(e)

[ 1 -1  3  4]
[1 2 3 4]


### Mathematics

In [66]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [67]:
a+2

array([3, 4, 5])

In [68]:
a-2

array([-1,  0,  1])

In [69]:
a/2

array([0.5, 1. , 1.5])

In [70]:
a*2

array([2, 4, 6])

In [71]:
a**2

array([1, 4, 9], dtype=int32)

In [72]:
# Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [73]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

### Linear Algebra

In [77]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [79]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [80]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
# Find the determinant
np.linalg.det(c)

1.0

### Statistics

In [82]:
stats = np.array([[1,2,2], [4,5,6]])
stats

array([[1, 2, 2],
       [4, 5, 6]])

In [83]:
np.min(stats)

1

In [85]:
np.min(stats, axis=1)

array([1, 4])

In [86]:
np.min(stats, axis=0)

array([1, 2, 2])

In [87]:
np.max(stats, axis=0)

array([4, 5, 6])

In [88]:
np.sum(stats)

20

In [89]:
np.sum(stats, axis=0)

array([5, 7, 8])

In [90]:
np.sum(stats, axis=1)

array([ 5, 15])

### Reorganising arrays

In [92]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [94]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [96]:
## Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v1, v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
## Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [98]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
h2

array([[0., 0.],
       [0., 0.]])

### Miscellaneous

#### Load data from file

In [100]:
filedata = np.genfromtext('data.txt', delimiter=',')
filedata = filedata.astype('int32')
# The error is showing due to the absence of data.txt 
# in the root file of the jupyter notebook

AttributeError: module 'numpy' has no attribute 'genfromtext'

### Advanced Indexing and Boolean Masking

In [ ]:
filedata > 50

## You will get array of falses and trues based on the condition you apply

In [ ]:
filedata[filedata > 50]

# This will give you the numerical values instead of boolean values

In [101]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])